site_name: Seer2Redev
nav:
  - 主页: index.md
  - 资料链接: link.md
  - Setup: setup.md
  - Usage: usage.md
  - Advanced Topics:
      - Customization: customization.md
      - Extensions: extensions.md
  - FAQ: faq.md
  - About: about.md

theme:
  name: material
  # 或者使用其他主题，如 'material'

# 配置插件
plugins:
  - search

# 自定义路径
docs_dir: docs  # 文档的目录，默认是 'docs'


# 配置额外信息，例如版权、联系信息等
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/你的GitHub账户

markdown_extensions:
  - toc:
      permalink: true